### PR TITLE
Improve check_process (level 4, author=user)

### PR DESCRIPTION
**Pull request by Jibec**
hi, we should force level 4 since LDAP integration doesn't make sense for this app (no need to deny level 4 or more)
add the "author" field as "USER", in hope it enables the tests to run.

### CODE REVIEW

**Comment by YliesC** [comment]
Good catch!

**Comment by Jibec** [comment]
Great to see you're so reactive :)

Would you be interested by a review of your package?

**Comment by YliesC** [comment]
Of course, feel free to make any suggestions and/or PR :)

**Comment by Jibec** [comment]
Great, can you please create a "testing" branch so I make my PR based on this?

What I'll do is PR with comment and advises, so you can do it yourself. I want to make sure you're still able to maintain it after the rewrite. And can do it at your rhythm.

Do you speak French? I have a tutorial to use package_check, but written in French. I'll be pleased to translate it if needed. Or do you already uses it?

Btw, you can join me on mastodon: I'm jibec on mamot.fr

**Pull request merged**
